
exports.up = function(knex) {
  return knex.raw(`
    CREATE TYPE user_status AS ENUM ('active', 'inactive');

    CREATE TABLE users(
        user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
        first_name TEXT NOT NULL,
        last_name TEXT NOT NULL,
        email TEXT NOT NULL,
        password TEXT NOT NULL,
        member_since TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        status user_status DEFAULT 'active' NOT NULL
    );
  `);
};

exports.down = function(knex) {
    return knex.raw(`
        DROP TABLE users;
        DROP TYPE user_status;
  `);
};
